# GLOBAL
quarkus:
  mongodb:
    connection-string: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_DB_PORT}
  log:
    level: INFO
    category:
      com.gargoylesoftware.htmlunit.level: ERROR

# DEV
"%dev":
  quarkus:
     mongodb:
       connection-string: mongodb://localhost:27017
     log:
       category:
         de.tko.level: DEBUG

# TEST
"%test":
  quarkus":
     mongodb:
       connection-string: mongodb://localhost:27017